# Generated by Django 6.0.3 on 2026-03-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_question_interview_interviewframes_interviewresponse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='completion_reason',
            field=models.CharField(blank=True, choices=[('all_questions_answered', 'All Questions Answered'), ('user_ended_early', 'User Ended Early'), ('timeout', 'Session Timeout'), ('malpractice_terminated', 'Security Violations'), ('error', 'Technical Error'), ('admin_cancelled', 'Admin Cancelled'), ('expired', 'Interview Expired'), ('not_started', 'Never Started')], help_text='Why the interview ended', max_length=30, null=True),
        ),
    ]
