# Generated by Django 5.2.10 on 2026-03-11 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('companies', '0003_alter_jobpost_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='skills',
            field=models.ManyToManyField(to='common.skill'),
        ),
    ]
