# Generated by Django 5.2.10 on 2026-03-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_jobpost_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='required_skills',
        ),
    ]
