# Generated by Django 5.2.12 on 2026-03-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_companyprofile_id_alter_jobpost_id'),
        ('companies', '0005_remove_jobpost_required_skills'),
    ]

    operations = [
    ]
