# Generated by Django 6.0.3 on 2026-03-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_merge_20260317_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
