# Generated by Django 5.2.12 on 2026-03-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_aptitudetest_id_alter_candidatetestattempt_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aptitudetest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='candidatetestattempt',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
