# Generated by Django 5.2.11 on 2026-02-12 10:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('incomplete', 'Incomplete'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='requested', max_length=20)),
                ('attempt_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('total_questions', models.IntegerField(default=15, help_text='Total questions in the interview')),
                ('questions_answered', models.IntegerField(default=0, help_text='Number of questions answered by student')),
                ('voice_interview_started', models.BooleanField(default=False, help_text='Did student start voice interview?')),
                ('voice_interview_completed', models.BooleanField(default=False, help_text='Did student complete all questions?')),
                ('completion_reason', models.CharField(blank=True, choices=[('all_questions_answered', 'All Questions Answered'), ('user_ended_early', 'User Ended Early'), ('timeout', 'Session Timeout'), ('error', 'Technical Error'), ('admin_cancelled', 'Admin Cancelled'), ('expired', 'Interview Expired'), ('not_started', 'Never Started')], help_text='Why the interview ended', max_length=30, null=True)),
                ('completion_percentage', models.FloatField(default=0.0, help_text='Percentage of interview completed (0-100)')),
                ('interview_duration_seconds', models.IntegerField(blank=True, help_text='Total interview duration in seconds', null=True)),
                ('has_audio_responses', models.BooleanField(default=False, help_text='Are audio responses saved in HDFS?')),
                ('has_video_recording', models.BooleanField(default=False, help_text='Is video recording available in Kafka?')),
                ('has_frame_data', models.BooleanField(default=False, help_text='Are frames available for analysis?')),
                ('audio_responses_count', models.IntegerField(default=0, help_text='Number of audio files saved')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending Processing'), ('processing', 'Processing'), ('analysis_complete', 'Analysis Complete'), ('report_generated', 'Report Generated'), ('report_sent', 'Report Sent'), ('failed', 'Processing Failed')], default='pending', help_text='Current processing status in pipeline', max_length=20)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_error', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('report_generated_at', models.DateTimeField(blank=True, null=True)),
                ('report_file_path', models.TextField(blank=True, help_text='Path to generated PDF report', null=True)),
                ('report_sent_at', models.DateTimeField(blank=True, null=True)),
                ('report_sent_to', models.EmailField(blank=True, help_text='Email address report was sent to', max_length=254, null=True)),
                ('approval_email_sent', models.BooleanField(default=False, help_text='Has approval email been sent?')),
                ('approval_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_email_sent', models.BooleanField(default=False, help_text='Has rejection email been sent?')),
                ('rejection_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('status_updated_at', models.DateTimeField(auto_now=True, help_text='Last status change timestamp')),
                ('overall_score', models.FloatField(blank=True, null=True)),
                ('technical_score', models.FloatField(blank=True, null=True)),
                ('communication_score', models.FloatField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('cheating_detected', models.BooleanField(default=False)),
                ('analysis_completed', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_interviews', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'interview_system_interview',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewFrames',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frames_file_path', models.TextField(blank=True, null=True)),
                ('total_frames', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kafka_session_id', models.CharField(blank=True, help_text='Session ID for frame streaming', max_length=255, null=True)),
                ('video_session_id', models.CharField(blank=True, help_text='Session ID for video chunk streaming', max_length=255, null=True)),
                ('storage_method', models.CharField(choices=[('hdfs', 'HDFS'), ('kafka', 'Kafka'), ('both', 'Both')], default='hdfs', max_length=20)),
                ('total_video_chunks', models.IntegerField(default=0, help_text='Number of video chunks recorded')),
                ('video_recording_started_at', models.DateTimeField(blank=True, null=True)),
                ('video_recording_ended_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_video_duration_seconds', models.IntegerField(blank=True, null=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='interview_system.interview')),
            ],
            options={
                'db_table': 'interview_system_interviewframes',
            },
        ),
        migrations.CreateModel(
            name='InterviewResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(max_length=255)),
                ('audio_file_path', models.TextField()),
                ('local_file_path', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interview_system.interview')),
            ],
            options={
                'db_table': 'interview_system_interviewresponse',
            },
        ),
        migrations.CreateModel(
            name='VoiceInterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_question_number', models.IntegerField(default=0)),
                ('current_stage', models.CharField(choices=[('intro', 'Introduction'), ('projects', 'Projects'), ('python', 'Python Skills'), ('statistics', 'Statistics'), ('ml', 'Machine Learning'), ('closing', 'Closing')], default='intro', max_length=20)),
                ('interview_context', models.JSONField(default=list)),
                ('session_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('error', 'Error')], default='not_started', help_text='Current status of voice interview session', max_length=20)),
                ('total_questions_in_session', models.IntegerField(default=15)),
                ('questions_with_audio_saved', models.IntegerField(default=0, help_text='Questions with audio successfully saved to HDFS')),
                ('last_question_answered_at', models.DateTimeField(blank=True, null=True)),
                ('voice_session_started_at', models.DateTimeField(blank=True, null=True)),
                ('voice_session_ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, help_text="Why the session ended: 'completed', 'user_ended', 'timeout', 'error'", max_length=50, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voice_session', to='interview_system.interview')),
            ],
            options={
                'db_table': 'voice_interview_sessions',
            },
        ),
    ]
