# Generated by Django 5.2.12 on 2026-03-16 14:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='candidate_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text='External UUID identifier (used by audio analysis API)', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_student',
            field=models.BooleanField(default=False, help_text='True if this user participates in mock interviews as a student'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('candidate', 'Candidate'), ('company', 'Company'), ('admin', 'Admin')], default='candidate', max_length=20),
        ),
        migrations.AlterModelTable(
            name='user',
            table='accounts_user',
        ),
    ]
