# Generated by Django 4.2.7 on 2025-06-16 19:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interview_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cv_score', models.FloatField(default=0)),
                ('face_detection_score', models.FloatField(default=0)),
                ('eye_movement_score', models.FloatField(default=0)),
                ('head_movement_score', models.FloatField(default=0)),
                ('transcript_score', models.FloatField(default=0)),
                ('content_quality_score', models.FloatField(default=0)),
                ('fluency_score', models.FloatField(default=0)),
                ('final_score', models.FloatField(default=0)),
                ('grade', models.CharField(blank=True, max_length=2)),
                ('analysis_details', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='interview_system.interview')),
            ],
        ),
    ]
