# Generated by Django 5.2.12 on 2026-03-12

from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('college', models.CharField(blank=True, max_length=200)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('year_of_study', models.IntegerField(blank=True, null=True)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('resume', models.FileField(blank=True, upload_to='resumes/')),
                ('is_active', models.BooleanField(default=True)),
                ('batch_id', models.CharField(default='', help_text='Complete Batch ID (not Project ID)', max_length=100)),
                ('interview_preference', models.CharField(choices=[('weekend', 'Preferably Weekend'), ('working_day', 'Working Day')], default='', help_text='When will you be available for Mock Interview?', max_length=20)),
                ('availability_slots', models.JSONField(default=list, help_text='Three preferred time slots with date, day, from_time, to_time')),
                ('availability_updated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]

