# Generated by Django 5.2.10 on 2026-03-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='test_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
