# Generated by Django 5.2.10 on 2026-03-10 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_application_test_scheduled_at'),
        ('candidates', '0007_alter_candidateprofile_phone'),
        ('companies', '0003_alter_jobpost_is_active'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('candidate', 'job')},
        ),
    ]
