# Generated by Django 5.2.12 on 2026-03-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_id'),
        ('applications', '0004_alter_application_unique_together'),
    ]

    operations = [
    ]
