# Generated by Django 5.2.12 on 2026-03-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_merge_20260317_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('test_scheduled', 'Test Scheduled'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('aptitude_passed', 'Aptitude Passed'), ('aptitude_failed', 'Aptitude Failed'), ('mock_passed', 'Mock Passed'), ('mock_failed', 'Mock Failed'), ('final_selected', 'Final Selected')], default='applied', max_length=20),
        ),
    ]
