# Generated by Django 5.2.10 on 2026-03-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_remove_candidateprofile_education_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
