# Generated by Django 5.2.12 on 2026-03-16 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_system', '0003_remove_interviewresponse_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interview_system.question'),
        ),
    ]
