# Generated by Django 5.2.11 on 2026-02-12 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='availability_slots',
            field=models.JSONField(default=list, help_text='Three preferred time slots with date, day, from_time, to_time'),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='availability_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='batch_id',
            field=models.CharField(default='', help_text='Complete Batch ID (not Project ID)', max_length=100),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='interview_preference',
            field=models.CharField(choices=[('weekend', 'Preferably Weekend'), ('working_day', 'Working Day')], default='', help_text='When will you be available for Mock Interview?', max_length=20),
        ),
    ]
