# Generated by Django 5.2.11 on 2026-02-18 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_system', '0002_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewresponse',
            name='question_id',
        ),
        migrations.AddField(
            model_name='interviewresponse',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='interview_system.question'),
        ),
    ]
