# Generated by Django 5.2.10 on 2026-03-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_aptitudetest_id_alter_candidatetestattempt_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetestattempt',
            name='aptitude_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidatetestattempt',
            name='coding_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidatetestattempt',
            name='skill_score',
            field=models.IntegerField(default=0),
        ),
    ]
