# Generated by Django 5.2.12 on 2026-03-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_aptitudetest_id_alter_candidatetestattempt_id'),
        ('assessments', '0003_candidatetestattempt_aptitude_score_and_more'),
    ]

    operations = [
    ]
