# Generated by Django 5.2.12 on 2026-03-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_merge_20260317_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetestattempt',
            name='communication_answers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
