# Generated by Django 5.2.12 on 2026-03-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_candidatetestattempt_communication_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatetestattempt',
            name='malpractice_log',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
