"""
Django settings for PlacementPortal project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

try:
    from dotenv import load_dotenv  # type: ignore
except Exception:
    load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

if load_dotenv:
    load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-eiyx(1r!_)h_2huf*zx$r9h*v5dk=&cos*4kq6keqvwt8czi57",
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "1").strip().lower() in {"1", "true", "yes", "on"}

ALLOWED_HOSTS = [h.strip() for h in os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",") if h.strip()]


# Application definition

INSTALLED_APPS = [
    'accounts',  # 👈 MUST be before apps that use User

    'candidates',
    'companies',
    'applications',
    'assessments',
    'interviews',
    'user_management',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

AUTH_USER_MODEL = 'accounts.User'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'PlacementPortal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'PlacementPortal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_ENGINE = os.getenv("DB_ENGINE", "sqlite").strip().lower()

if DB_ENGINE in {"mysql", "django.db.backends.mysql"}:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": os.getenv("DB_NAME", "placementportal"),
            "USER": os.getenv("DB_USER", "root"),
            "PASSWORD": os.getenv("DB_PASSWORD", ""),
            "HOST": os.getenv("DB_HOST", "localhost"),
            "PORT": os.getenv("DB_PORT", "3306"),
        }
    }
else:
    # Default to SQLite so the project boots without external dependencies.
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "")

LOGIN_REDIRECT_URL = '/accounts/redirect/'

OPENROUTER_CONFIG = {
    "BASE_URL": os.getenv("OPENROUTER_BASE_URL", "https://openrouter.ai/api/v1"),
    "API_KEY": os.getenv("OPENROUTER_API_KEY", ""),
    "MODEL": os.getenv("OPENROUTER_MODEL", "deepseek/deepseek-r1-0528"),
}

HDFS_CONFIG = {
    "HOST": os.getenv("HDFS_HOST", "namenode"),      # 'namenode' = docker service name
    "PORT": int(os.getenv("HDFS_PORT", "9870")),
    "USER": os.getenv("HDFS_USER", "hdfs"),
    # HDFS directory layout
    "QUESTIONS_DIR": "/questions",
    "RESPONSES_DIR": "/responses",
    "FRAMES_DIR": "/frames",
}

# ── Kafka (frame + video streaming during interview) ──────────────────────────
_kafka_servers_raw = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "kafka:9092")
KAFKA_CONFIG = {
    "bootstrap_servers": [s.strip() for s in _kafka_servers_raw.split(",") if s.strip()],
    "frame_topic": os.getenv("KAFKA_FRAME_TOPIC", "interview-frames"),
    "video_topic": os.getenv("KAFKA_VIDEO_TOPIC", "interview-videos"),
    "timeout": int(os.getenv("KAFKA_TIMEOUT", "10")),
}

# ── Speech-to-Text (local Whisper via faster-whisper) ────────────────────────
STT_CONFIG = {
    "PROVIDER": os.getenv("STT_PROVIDER", "faster_whisper"),
    "MODEL_SIZE": os.getenv("WHISPER_MODEL_SIZE", "tiny.en"),
    "DEVICE": os.getenv("WHISPER_DEVICE", "cpu"),
    "COMPUTE_TYPE": os.getenv("WHISPER_COMPUTE_TYPE", "int8"),
    "CPU_THREADS": int(os.getenv("WHISPER_CPU_THREADS", "4")),
    "NUM_WORKERS": int(os.getenv("WHISPER_NUM_WORKERS", "1")),
    "LANGUAGE": os.getenv("WHISPER_LANGUAGE", "en"),
}

# ── Flask Audio Analysis microservice URL ─────────────────────────────────────
# Django calls this to trigger post-interview audio analysis
AUDIO_API_BASE_URL = os.getenv("AUDIO_API_BASE_URL", "http://audio_api:5000")

# ── CSRF / Security ───────────────────────────────────────────────────────────
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.getenv("CSRF_TRUSTED_ORIGINS", "http://localhost").split(",")
    if o.strip()
]

VOICE_INTERVIEW_TTS_ENABLED = os.getenv("VOICE_INTERVIEW_TTS_ENABLED", "").lower() in {"1", "true", "yes", "on"}

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
