# Generated by Django 5.2.10 on 2026-03-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='education',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='experience',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='skills',
            field=models.TextField(blank=True),
        ),
    ]
