# Generated by Django 5.2.10 on 2026-03-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidateprofile_education_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='experience',
        ),
    ]
