# Generated by Django 5.2.10 on 2026-03-05 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_alter_candidateprofile_resume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='skills',
            new_name='resume_text',
        ),
    ]
