# Generated by Django 5.2.10 on 2026-03-05 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_rename_skills_candidateprofile_resume_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateprofile',
            old_name='resume_text',
            new_name='extracted_skills',
        ),
    ]
