# Generated by Django 5.2.10 on 2026-03-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_rename_resume_text_candidateprofile_extracted_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidateprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
