# Generated by Django 5.2.12 on 2026-03-17 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0008_alter_candidateprofile_id'),
        ('candidates', '0008_candidateprofile_skills'),
    ]

    operations = [
    ]
