# Generated by Django 6.0.3 on 2026-03-24 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_merge_20260317_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='backlogs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='cgpa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='college_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='degree',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
