# Generated by Django 6.0.3 on 2026-03-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0010_candidateprofile_backlogs_candidateprofile_cgpa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='course_duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='course_specialization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='differently_abled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='domain',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='graduating_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='user_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
